### ISSUE TITLE
Yeah! I automatically took a profitable trade last night for the first time :D

### ISSUE THREAD

**Issue by MeoMix** [etherdelta/bots#2]
Just thought you should know given the journey I've been on trying to get this shit up and running.

Unfortunately (and word of warning for anyone else reading), I thiiiiiiiiink game theory says that this actually can't be a profitable endeavor. Sort of like prisoner's dilemma. I didn't actually make money running last night due to being beaten out by others at a rate that makes the amount I pay in gas fees not sustainable.

Sooo I'm going to take a day of rest, then get started on capturing trade data and working on market making.

@zackcoburn Is your understanding that it's not actually profitable to try and run one of these typo-buying bots? People will just increase their bots gas usage until all the profits disappear. There's always a chance you lose out -- either being a block behind the successful trade, or failing to pay as much in gas as the other bot. Some bots pay 50% fees. I ran with 55% fees as gas last night and had 3 successful trades out of 18. So, on average, running at a loss still. Does that align with your understanding? Any ideas on other clever things I could try to make profits while building up to market making? :)

**Comment by zackcoburn** [comment]
Congratulations!

It's definitely my understanding that this kind of bot will always be a
gas-price-game-theory-war-of-attrition.

Zack Coburn

NOTICE: This e-mail transmission (and/or the attachments accompanying it)
may contain confidential information belonging to the sender which is
protected by law. The information is intended only for the use of the
intended recipient. If you are not the intended recipient, you are hereby
notified that any disclosure, copying, distribution or the taking of any
action in reliance on the contents of this information is strictly
prohibited. Any unauthorized interception of this transmission is illegal.
If you have received this transmission in error, please promptly notify the
sender by reply e-mail, and then destroy all copies of the transmission.

**Comment by MeoMix** [comment]
Thanks!!

Do you think basic market making on high spread coins is the next most simple strategy to employ? I'm trying to work my way up through the basics. I figured typo buying was the simplest strategy. Then playing the spread on ED (vs like... Bitcoin on GDAX where there is no spread).

I think this is simpler because you don't have to have as much predictive analysis on where the price is going since there's not always enough liquidity on coins here... the price of coins are less likely to stay in a trade channel on ED though..

**Comment by zackcoburn** [comment]
I will say that the main thing I've been hoping to get out of releasing the
new API and example bots is (more?) automated market makers.

**Comment by MeoMix** [comment]
Welp, that's what my next week of efforts will be on. Hopefully I have better success with it than purchasing typos. :) I suspect I will... trying to get a market maker algorithm successfully running before Ethfinex goes live.
